Carousel Feature
gjuliao/car_app_frontend pull request #37
Opened 2023-05-09 20:31 UTC by gjuliao

## Requirement
- Add carousel future to preview cars on Desktop and mobile.
- Fixed footer.

2023-05-09 21:54 UTC, belaymit requested changes
# Status: Changes Required

- [ ] Linters are passing
- [ ] Nice implementation
- [ ] Nice use of methods
However, there are some changes you need to work on: see the comment below

2023-05-09 21:54 UTC, belaymit commented on src/components/ProductSlider.jsx
> +        <SwiperSlide>
I think we can use loop or map method in order to avoid repetition

2023-05-10 18:27 UTC, gjuliao commented
Hi @belaymit the fetching has been applied within a map function to avoid duplicate code.

Let me know your thoughts on the new design.

2023-05-10 18:31 UTC, belaymit approved these changes
# Status: Approved

- Nice work Giovanni! 
- please merge it

2023-05-10 18:32 UTC, merged

2023-05-10 18:32 UTC, gjuliao commented
Awesome @belaymit !